services:
  soldier1:
    build: .
    networks:
      - nodes
    environment:
      - SERVICE_NAME=soldier1

  soldier2:
    build: .
    networks:
      - nodes
    environment:
      - SERVICE_NAME=soldier2

networks:
  nodes: